

spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/call_db?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 6040
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        default_batch_fetch_size: 100
  profiles:
    active: dev


shop:
  app:
    jwtSecret: testSecretKey
    jwtExpirationMs: 6000000



server:
  port: 7001





logging:
  level:
    org.hibernate.SQL: debug