

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/call_db?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 6040
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        default_batch_fetch_size: 100
        # where in(100) 파라미터 갯수 지정
        # 일대다 N 컬렉션 100개 데이터를 1번 쿼리 실행
        # 데이터가 1000개이면 1000/100= 10번 쿼리 실행
  profiles:
    active: dev






server:
  port: 7001





logging:
  level:
    org.hibernate.SQL: debug